# Ignora todo lo que pueda ser binario o artefacto de build
exclude_paths:
  - ".git/**"
  - "Sandbox/**"
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.dll"
  - "**/*.exe"
  - "**/*.pdb"
  - "**/*.cache"
  - "**/*.meta"
  - "**/*.assets.cache"
  - "**/apphost.exe"
